# Support Python 3.10+
target-version = "py310"
line-length = 88

[lint]
# Enable Pyflakes (F), Pycodestyle (E, W), Isort (I), and Naming (N)
select = ["F", "E", "W", "I", "N"]
ignore = []

# Allow fixable errors to be fixed automatically
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"